### ISSUE TITLE
MSE Evaluation of the human heart data

### ISSUE THREAD

**Issue by Epoch1128** [JiawenChenn/POLARIS#1]
I can find the processed ST and ScRNA data in the directory of _data_. And I think the file **ISS/PCW6.5_1_st_cnt.genexrow.tsv** will be the ST data derived from the raw heart data(Cell 2019) and the file **ISS/ref/internal/PCW6.5_1_scRNA.cnt.tsv** is the processed single cell data. My problems are the request for the raw data and how to convert the raw data to these 2 files. Thanks!

**Comment by JiawenChenn** [comment]
Hi, the raw data could be accessed through the original publication (https://github.com/Moldia/heart). We treated each read of a gene in a cell as a count and sum them up as the gene expression count in that cell.

**Comment by Epoch1128** [comment]
It really helps! Thanks a lot!
