### ISSUE TITLE
The module models_mae in datasets.py

### ISSUE THREAD

**Issue by hehuifeng** [JiawenChenn/POLARIS#2]
Hello, I tried to use your software to run my data, but I don't understand that there is _import models_mae_ in the _datasets.py_, may I ask where can I find this module?

**Comment by JiawenChenn** [comment]
Hi Huifeng,

Thanks for bringing this up. You could download it from https://github.com/facebookresearch/mae/.

**Comment by hehuifeng** [comment]
Thank you for your reply! I have already downloaded, the module was successfully imported into my project. Thank you for your help!
