### ISSUE TITLE
the problem about heart_4layer.tsv

### ISSUE THREAD

**Issue by ChyLeeX** [JiawenChenn/POLARIS#3]
Hello, Chen! Thank you for proposing a novel deconvolution method. I'm very interested in this approach, but when I try to run the example dataset you gave, I can't find the heart_4layer.tsv file. May I ask where can I find this file?
Thank you very much!

**Comment by JiawenChenn** [comment]
Hi, thanks for bringing this up. I have uploaded the file to data/heart/ISS/.

**Comment by ChyLeeX** [comment]
> Hi, thanks for bringing this up. I have uploaded the file to data/heart/ISS/.

Thanks for your prompt reply, I've been able to run your example data!
