### ISSUE TITLE
NaN values and -ve values in meta vector post sc training

### ISSUE THREAD

**Issue by ajitashree** [JiawenChenn/POLARIS#6]
Dear authors,

We are running Polaris for spot deconvolution task. We have added the feature of reading spatial and single-cell data as .h5ad in the Polaris codebase. However, we are running into "Index out of range" error, please see attached. We have also printed the vectors, they seem to have NaN values.
[Polaris Issue.pdf](https://github.com/JiawenChenn/POLARIS/files/14756323/Polaris.Issue.pdf)
<img width="1408" alt="Screenshot 2024-03-26 at 3 19 43 PM" src="https://github.com/JiawenChenn/POLARIS/assets/13568525/b58cc65b-65b0-4b3f-af13-f2f81ddeb4d7">

Could you please help us resolve the issue?

Thanks,
Ajita

**Comment by JiawenChenn** [comment]
Hi, seems that the layer information and spatial coordinates are missing. You can use clustering methods like Kmeans, BayesSpace to get the spatial domain information for the ST data.

**Comment by ajitashree** [comment]
Dear Jiawen,  

Thanks you, we are able to fix the issue based your suggestion.
